
import type { PlanningTerm } from '@/types';

// Sourced from various UK government and planning-related websites.
const planningTerms: PlanningTerm[] = [
  {
    id: '1app',
    term: '1APP',
    category: 'Development',
    definition: 'The standard planning application form for England and Wales (except minerals). Streamlines the application process across authorities.',
  },
  {
    id: 'access',
    term: 'Access',
    category: 'Access',
    definition: 'How a site connects to highways or public transport. A key consideration in planning applications.',
  },
  {
    id: 'adopted-proposals-map',
    term: 'Adopted Proposals Map',
    category: 'Planning Policy',
    definition: 'A map showing land allocations and designations in an adopted local plan. Guides planning decisions by defining areas for housing, industry, or protection.',
  },
  {
    id: 'adoption',
    term: 'Adoption',
    category: 'Legal',
    definition: 'The formal process by which a public body, such as a highway authority or a water company, takes on the future responsibility for maintaining infrastructure (e.g., roads, sewers) constructed by a developer.',
  },
  {
    id: 'advertisement-control',
    term: 'Advertisement Control',
    category: 'Enforcement',
    definition: 'The process to assess if advertisements are acceptable for amenity and safety.'
  },
  {
    id: 'advocacy',
    term: 'Advocacy',
    category: 'Legal',
    definition: 'Support for a planning proposal or appeal, often by a planning barrister or solicitor. Used in inquiries to argue a case before an inspector.',
  },
  {
    id: 'affordable-housing',
    term: 'Affordable Housing',
    category: 'Housing',
    definition: 'Housing for sale or rent for those whose needs are not met by the market (including social rented, affordable rented and intermediate housing). LPAs can require developers to provide a percentage of affordable housing in new developments.',
  },
  {
    id: 'agent',
    term: 'Agent',
    category: 'Legal',
    definition: 'A professional, often a planning consultant or architect, who prepares and submits a planning application.'
  },
  {
    id: 'agent-of-change-principle',
    term: 'Agent of Change Principle',
    category: 'Development',
    definition: 'This principle states that the person or business responsible for a change is responsible for managing the impact of that change. For example, if a new residential development is built near an existing music venue, the developer is responsible for ensuring residents are not unduly affected by noise.',
  },
  {
    id: 'agenda',
    term: 'Agenda',
    category: 'Legal',
    definition: 'A schedule of items for discussion at a planning committee meeting. Outlines applications and issues to be decided by councillors.',
  },
  {
    id: 'agricultural-dwelling',
    term: 'Agricultural Dwelling',
    category: 'Housing',
    definition: 'A house restricted to occupancy by someone employed mainly in agriculture, forestry, or similar rural work.'
  },
  {
    id: 'agricultural-permitted-development',
    term: 'Agricultural Permitted Development',
    category: 'Development',
    definition: 'Certain works on agricultural land that do not require formal planning permission.'
  },
  {
    id: 'allocated-land',
    term: 'Allocated Land',
    category: 'Land Use',
    definition: 'Land designated in a local plan for specific uses like housing or retail. Ensures planned development aligns with community needs.',
  },
  {
    id: 'amend-amendment',
    term: 'Amend/Amendment',
    category: 'Development',
    definition: 'Changes made to a planning application or development plan. May require further consultation or approval from the local authority.',
  },
  {
    id: 'amenity',
    term: 'Amenity',
    category: 'Development',
    definition: 'A general term for the positive elements that contribute to the overall character or enjoyment of an area. Planning decisions often consider the potential impact of a development on the amenity of neighbouring residents (e.g., noise, privacy, light).',
  },
  {
    id: 'ancillary-use',
    term: 'Ancillary Use',
    category: 'Land Use',
    definition: 'A use of land or a building that is subordinate to, and functionally connected with, the primary use of that land or building. A use is ancillary if it is not a separate planning unit, such as a home office being ancillary to a dwelling.',
  },
  {
    id: 'ancient-monument',
    term: 'Ancient Monument',
    category: 'Heritage',
    definition: 'A legally protected historic structure or site. Development nearby must consider its setting and preservation.',
  },
  {
    id: 'ancient-woodland',
    term: 'Ancient Woodland',
    category: 'Environment',
    definition: 'Woods with continuous cover since at least 1600 AD.',
  },
  {
    id: 'annual-monitoring-report-amr',
    term: 'Annual Monitoring Report (AMR)',
    category: 'Planning Policy',
    definition: 'A yearly report assessing progress on local plan policies and targets. Includes data on housing delivery and Gypsy and Traveller site provision.',
  },
  {
    id: 'appeal',
    term: 'Appeal',
    category: 'Legal',
    definition: 'A process to challenge a planning decision, such as refusal or conditions, handled by the Planning Inspectorate.'
  },
  {
    id: 'appearance',
    term: 'Appearance',
    category: 'Development',
    definition: 'The external look of a building or development, considered in planning decisions. Influences design quality and compatibility with surroundings.',
  },
  {
    id: 'applicant',
    term: 'Applicant',
    category: 'Legal',
    definition: 'The person or organization submitting a planning application. May hire an agent to manage the process on their behalf.',
  },
  {
    id: 'arboriculture',
    term: 'Arboriculture',
    category: 'Environment',
    definition: 'The management and care of trees and shrubs in planning contexts. Ensures trees are protected or integrated into development designs.',
  },
  {
    id: 'area-of-outstanding-natural-beauty-aonb',
    term: 'Area of Outstanding Natural Beauty (AONB)',
    category: 'Conservation',
    definition: 'An area of countryside in England, Wales or Northern Ireland that has been designated for conservation due to its significant landscape value. Development in AONBs is subject to strict controls.',
  },
  {
    id: 'article-4-direction',
    term: 'Article 4 Direction',
    category: 'Legal',
    definition: 'An order made by an LPA that removes specific permitted development rights in a defined area. It means that a formal planning application is required for work that would otherwise not need one.',
  },
  {
    id: 'best-possible-environmental-option-bpeo',
    term: 'Best Possible Environmental Option (BPEO)',
    category: 'Environment',
    definition: 'An option balancing environmental benefits with acceptable costs.'
  },
  {
    id: 'best-value-performance-indicators-bvpis',
    term: 'Best Value Performance Indicators (BVPIs)',
    category: 'Legal',
    definition: 'Metrics to assess local authority performance in planning and service delivery. Now largely replaced but historically used to monitor efficiency.',
  },
  {
    id: 'biodiversity',
    term: 'Biodiversity',
    category: 'Environment',
    definition: 'The variety and abundance of species in a given area.'
  },
  {
    id: 'biodiversity-action-plan',
    term: 'Biodiversity Action Plan',
    category: 'Environment',
    definition: 'A UK plan to meet global commitments to protect priority species and habitats.'
  },
  {
    id: 'biodiversity-net-gain-bng',
    term: 'Biodiversity Net Gain (BNG)',
    category: 'Environment',
    definition: 'A mandatory requirement for most new developments in England to deliver a measurable improvement (at least 10%) for biodiversity. It ensures that development leaves the natural environment in a better state than it was before.',
  },
  {
    id: 'blight-notice',
    term: 'Blight Notice',
    category: 'Legal',
    definition: 'A notice allowing landowners to force the purchase of land affected by planning decisions.'
  },
  {
    id: 'breach-of-condition-notice',
    term: 'Breach of Condition Notice',
    category: 'Enforcement',
    definition: 'A notice served by a local planning authority when a condition attached to a planning permission is not being complied with. There is no right of appeal against such a notice.',
  },
  {
    id: 'breach-of-planning-control',
    term: 'Breach of Planning Control',
    category: 'Enforcement',
    definition: 'Carrying out development without the required planning permission, or failing to comply with any condition or limitation subject to which planning permission has been granted.',
  },
  {
    id: 'brownfield-land',
    term: 'Brownfield Land',
    category: 'Land Use',
    definition: 'Land which has been previously developed, excluding land that was agricultural or forestry-related. Government policy generally encourages the use of brownfield sites for new development over greenfield sites.',
  },
  {
    id: 'building-control',
    term: 'Building Control',
    category: 'Development',
    definition: 'The service, provided either by the local authority or an Approved Inspector, that checks building work to ensure it complies with the Building Regulations. They carry out site inspections and issue a completion certificate.',
  },
  {
    id: 'building-preservation-order',
    term: 'Building Preservation Order',
    category: 'Heritage',
    definition: 'A notice to protect buildings of special architectural or historic interest from demolition or alteration.'
  },
  {
    id: 'building-regulations',
    term: 'Building Regulations',
    category: 'Development',
    definition: 'National standards for the design and construction of buildings to ensure their health, safety, welfare and convenience, as well as fuel and power conservation. Approval is a separate process from planning permission.',
  },
  {
    id: 'building-research-establishment-environmental-assessment-method-breeam',
    term: 'Building Research Establishment Environmental Assessment Method (BREEAM)',
    category: 'Environment',
    definition: 'A leading sustainability assessment method for masterplanning projects, infrastructure and buildings. It sets standards for the environmental performance of buildings through the design, specification, construction and operational phases.',
  },
  {
    id: 'business-improvement-districts-bids',
    term: 'Business Improvement Districts (BIDs)',
    category: 'Development',
    definition: 'Areas where businesses fund projects to improve the local environment. May influence planning through enhanced public realm or infrastructure.',
  },
  {
    id: 'call-in',
    term: 'Call-in',
    category: 'Legal',
    definition: 'The power of the Secretary of State to take the decision-making power on a particular planning application away from the local planning authority. This is typically reserved for applications of more than local importance.',
  },
  {
    id: 'cdm-regulations-construction-design-and-management',
    term: 'CDM Regulations (Construction, Design and Management)',
    category: 'Legal',
    definition: 'The main set of regulations for managing health, safety and welfare on construction projects. They apply to all building and construction work and define key duty holders like the Client, Principal Designer and Principal Contractor.',
  },
  {
    id: 'certificate-of-appropriate-alternative-development',
    term: 'Certificate of Appropriate Alternative Development',
    category: 'Legal',
    definition: 'An assessment of whether alternative development could have been permitted on compulsorily purchased land.',
  },
  {
    id: 'certificate-of-immunity',
    term: 'Certificate of Immunity',
    category: 'Heritage',
    definition: 'A certificate that may be granted by Historic England which gives immunity from a building being listed for a period of five years. It is often sought before undertaking works to an unlisted building in a sensitive area.',
  },
  {
    id: 'certificate-of-lawfulness',
    term: 'Certificate of Lawfulness',
    category: 'Legal',
    definition: 'A certificate confirming a proposed or existing use or development is lawful.'
  },
  {
    id: 'change-of-use',
    term: 'Change of Use',
    category: 'Land Use',
    definition: 'Altering the purpose of a building or land, such as from shop to residential.'
  },
  {
    id: 'character',
    term: 'Character',
    category: 'Development',
    definition: 'The distinct identity of a place, shaped by its landscape, streets, or buildings.'
  },
  {
    id: 'character-appraisal',
    term: 'Character Appraisal',
    category: 'Conservation',
    definition: 'A document that defines the special architectural or historic interest that warrants the designation of a Conservation Area. It provides a basis for making informed planning decisions and developing policies to manage change.',
  },
  {
    id: 'chartered',
    term: 'Chartered',
    category: 'Legal',
    definition: 'A professional qualification, such as a chartered planner or surveyor. Indicates expertise in planning or related fields.',
  },
  {
    id: 'circulars',
    term: 'Circulars',
    category: 'Planning Policy',
    definition: 'Government-issued guidance explaining planning law or policy in detail. Often supports legislation, like Technical Advice Notes in Wales.',
  },
  {
    id: 'code-of-conduct',
    term: 'Code of Conduct',
    category: 'Legal',
    definition: 'Rules ensuring fair and transparent planning decisions.'
  },
  {
    id: 'commencement-of-development',
    term: 'Commencement of Development',
    category: 'Development',
    definition: 'The point at which development is legally considered to have begun, which "keeps a planning permission alive". This is typically triggered by a "material operation" such as digging a trench for foundations or laying a new access road.',
  },
  {
    id: 'commitments',
    term: 'Commitments',
    category: 'Development',
    definition: 'Land with current planning permission or allocated in local plans. Tracks development potential for housing or other uses.',
  },
  {
    id: 'committee-report',
    term: 'Committee Report',
    category: 'Legal',
    definition: 'A report by planning officers to the planning committee summarizing an application. Includes recommendations, conditions, or reasons for refusal.',
  },
  {
    id: 'community-infrastructure-levy-cil',
    term: 'Community Infrastructure Levy (CIL)',
    category: 'Development',
    definition: 'A charge which local authorities can set on new development in their area to help fund local infrastructure. It is a non-negotiable, tariff-based system with rates set out in a "Charging Schedule".',
  },
  {
    id: 'community-strategy',
    term: 'Community Strategy',
    category: 'Planning Policy',
    definition: 'A high-level plan to improve public services and facilities in an area. Informs local planning and aligns with spatial objectives.',
  },
  {
    id: 'community-town-councils',
    term: 'Community/Town Councils',
    category: 'Legal',
    definition: 'Local bodies consulted on planning applications in their area. Represent community interests but lack decision-making powers.',
  },
  {
    id: 'condition-precedent',
    term: 'Condition Precedent',
    category: 'Legal',
    definition: 'A planning condition that must be formally discharged (approved) by the Local Planning Authority *before* any development commences on site. Failure to discharge a condition precedent can invalidate the entire planning permission.',
  },
  {
    id: 'conditions',
    term: 'Conditions',
    category: 'Legal',
    definition: 'Requirements attached to planning permission to control how development is carried out.'
  },
  {
    id: 'conditions-of-planning-permission',
    term: 'Conditions of Planning Permission',
    category: 'Development',
    definition: 'Requirements attached to a grant of planning permission to ensure that the development is acceptable. For example, conditions might restrict operating hours or require the use of specific building materials.',
  },
  {
    id: 'confidential',
    term: 'Confidential',
    category: 'Legal',
    definition: 'Information in planning processes not disclosed to the public. Protects sensitive personal or commercial interests.',
  },
  {
    id: 'conservation-area',
    term: 'Conservation Area',
    category: 'Conservation',
    definition: 'An area designated for its special architectural or historic interest, the character or appearance of which it is desirable to preserve or enhance. Development within these areas is subject to stricter planning controls.',
  },
  {
    id: 'conservation-area-consent',
    term: 'Conservation Area Consent',
    category: 'Conservation',
    definition: 'Permission needed for demolition in a conservation area.'
  },
  {
    id: 'consult-consultation',
    term: 'Consult/Consultation',
    category: 'Legal',
    definition: 'The process of seeking public or stakeholder input on planning matters. Can be formal (e.g., for local plans) or informal (e.g., for applications).',
  },
  {
    id: 'consultation-bodies',
    term: 'Consultation Bodies',
    category: 'Legal',
    definition: 'Organizations statutorily required to be consulted on planning applications or plans. Include bodies like Natural England or Historic England.',
  },
  {
    id: 'contamination-contaminated-land',
    term: 'Contamination/Contaminated Land',
    category: 'Environment',
    definition: 'Land polluted and unfit for development without cleanup. Planning requires remediation to ensure safety.',
  },
  {
    id: 'core-strategy',
    term: 'Core Strategy',
    category: 'Planning Policy',
    definition: 'The main part of a local plan, setting out key development policies.'
  },
  {
    id: 'county-councils',
    term: 'County Councils',
    category: 'Legal',
    definition: 'Local authorities responsible for waste, minerals, and their own developments. Act as highways authorities in two-tier systems.',
  },
  {
    id: 'court-of-human-rights',
    term: 'Court of Human Rights',
    category: 'Legal',
    definition: 'The European Court addressing human rights issues in planning disputes. Rarely involved but relevant for rights-based challenges.',
  },
  {
    id: 'cross-examine',
    term: 'Cross-Examine',
    category: 'Legal',
    definition: 'Questioning a witness during a planning inquiry to test evidence. Conducted by legal professionals under an inspector’s oversight.',
  },
  {
    id: 'cross-laminated-timber-clt',
    term: 'Cross Laminated Timber (CLT)',
    category: 'Development',
    definition: 'An engineered wood product increasingly used in construction for its strength, sustainability, and speed of erection. It consists of layers of timber glued together at right angles.',
  },
  {
    id: 'curtilage',
    term: 'Curtilage',
    category: 'Property',
    definition: 'The area of land attached to a house and forming one enclosure with it. The legal definition is important for determining permitted development rights and defining the extent of a residential planning unit.',
  },
  {
    id: 'custom-and-self-build-register',
    term: 'Custom and Self-Build Register',
    category: 'Housing',
    definition: 'A register that all local authorities in England are required to keep of people and associations who are seeking to acquire serviced plots of land in the authority\'s area to build their own homes.',
  },
  {
    id: 'decision-notice',
    term: 'Decision Notice',
    category: 'Legal',
    definition: 'A formal document stating the local authority’s decision on a planning application.'
  },
  {
    id: 'deemed-consent',
    term: 'Deemed Consent',
    category: 'Legal',
    definition: 'Automatic permission for certain advertisements under regulations.'
  },
  {
    id: 'defer',
    term: 'Defer',
    category: 'Legal',
    definition: 'Postponing a planning decision to a later date. Allows time to gather more information or resolve issues.',
  },
  {
    id: 'delegated-powers',
    term: 'Delegated Powers',
    category: 'Legal',
    definition: 'The authority given by a council to its planning officers to make decisions on certain planning applications (typically smaller or less controversial ones) without them having to be decided by the Planning Committee. This covers the vast majority of applications.',
  },
  {
    id: 'delivery-agreement',
    term: 'Delivery Agreement',
    category: 'Planning Policy',
    definition: 'A document outlining the timetable and community involvement for local plan preparation. Required in Wales and agreed with the Welsh Government.',
  },
  {
    id: 'density-housing',
    term: 'Density (Housing)',
    category: 'Housing',
    definition: 'The number of homes or habitable rooms per unit of land area. Guides development intensity in local plans.',
  },
  {
    id: 'departure',
    term: 'Departure',
    category: 'Development',
    definition: 'A proposed development that deviates from the adopted local plan. Requires justification and may face stricter scrutiny.',
  },
  {
    id: 'deposit',
    term: 'Deposit',
    category: 'Planning Policy',
    definition: 'The public consultation phase for a draft local plan before examination. Comments shape the final plan reviewed by an inspector.',
  },
  {
    id: 'design',
    term: 'Design',
    category: 'Development',
    definition: 'The aesthetic and functional aspects of a building or development. Influences planning decisions to ensure quality and context fit.',
  },
  {
    id: 'design-and-access-statement-das',
    term: 'Design and Access Statement (DAS)',
    category: 'Development',
    definition: 'A document that accompanies certain types of planning application, explaining the design principles and concepts that have been applied to the proposed development. It must also demonstrate how access issues have been considered.',
  },
  {
    id: 'design-code',
    term: 'Design Code',
    category: 'Development',
    definition: 'A set of illustrated design requirements that provide specific, detailed parameters for the physical development of a site or area. They build on a design vision, such as a masterplan, to provide instructions for developers.',
  },
  {
    id: 'designated-heritage-asset',
    term: 'Designated Heritage Asset',
    category: 'Heritage',
    definition: 'A World Heritage Site, Scheduled Monument, Listed Building, Protected Wreck Site, Registered Park and Garden, or Conservation Area, as designated under the relevant legislation.',
  },
  {
    id: 'detailed-application',
    term: 'Detailed Application',
    category: 'Development',
    definition: 'An application with full details of a proposed development. Unlike outline applications, it includes specifics like design and access.',
  },
  {
    id: 'development',
    term: 'Development',
    category: 'Development',
    definition: 'Building, engineering, mining, or material change in land use as defined by the Town and Country Planning Act 1990.'
  },
  {
    id: 'development-management',
    term: 'Development Management',
    category: 'Planning Policy',
    definition: 'The process of handling planning applications and enforcing rules.'
  },
  {
    id: 'development-plan',
    term: 'Development Plan',
    category: 'Planning Policy',
    definition: 'The statutory framework guiding planning decisions, including local and neighbourhood plans.',
  },
  {
    id: 'development-plan-document-dpd',
    term: 'Development Plan Document (DPD)',
    category: 'Planning Policy',
    definition: 'A statutory document forming part of the local development framework, setting out planning policies.',
  },
  {
    id: 'discharge-of-conditions',
    term: 'Discharge of Conditions',
    category: 'Legal',
    definition: 'The formal process of submitting details to the LPA for their approval in order to satisfy the requirements of a planning condition. This is a common step after permission has been granted but before or during construction.',
  },
  {
    id: 'duty-to-cooperate',
    term: 'Duty to Cooperate',
    category: 'Planning Policy',
    definition: 'A legal test that required local planning authorities and other public bodies to engage constructively and actively on an ongoing basis on strategic planning matters. It was recently replaced by a new "Alignment Policy" approach, but the principle of cooperation remains.',
  },
  {
    id: 'enforcement-action',
    term: 'Enforcement Action',
    category: 'Enforcement',
    definition: 'Steps taken by a local authority to address unauthorized development.'
  },
  {
    id: 'enforcement-notice',
    term: 'Enforcement Notice',
    category: 'Enforcement',
    definition: 'A formal notice served by an LPA on a landowner where a breach of planning control has occurred (e.g., development without permission). The notice specifies the breach and the steps required to remedy it within a given timeframe.',
  },
  {
    id: 'enterprise-zone',
    term: 'Enterprise Zone',
    category: 'Development',
    definition: 'An area designated to encourage business growth through simplified planning and tax incentives.',
  },
  {
    id: 'environmental-impact-assessment-eia',
    term: 'Environmental Impact Assessment (EIA)',
    category: 'Environment',
    definition: 'A systematic process to identify, predict and evaluate the environmental effects of proposed developments. It is a legal requirement for certain types of large-scale projects before planning permission can be granted.',
  },
  {
    id: 'equality-impact-assessment',
    term: 'Equality Impact Assessment',
    category: 'Environment',
    definition: 'An evaluation of a plan’s impact on protected groups under equality law. Ensures fair outcomes in planning policies.',
  },
  {
    id: 'established-use-certificate',
    term: 'Established Use Certificate',
    category: 'Legal',
    definition: 'A pre-1992 certificate proving a use existed before 1964, granting immunity from enforcement. Replaced by Lawful Development Certificates.'
  },
  {
    id: 'evidence-base',
    term: 'Evidence Base',
    category: 'Planning Policy',
    definition: 'The collection of research, data, and analysis that underpins and justifies the policies and proposals in a Local Plan. This includes assessments on housing need, employment land, transport, and environmental constraints.',
  },
  {
    id: 'examination-in-public-eip',
    term: 'Examination in Public (EIP)',
    category: 'Planning Policy',
    definition: 'The process by which an independent Planning Inspector examines the soundness of a Local Plan. The Inspector assesses whether the plan has been prepared in line with legal and procedural requirements and is effective and justified.',
  },
  {
    id: 'express-consent',
    term: 'Express Consent',
    category: 'Legal',
    definition: 'Permission required for advertisements not covered by deemed consent.'
  },
  {
    id: 'five-year-housing-land-supply-5yhls',
    term: 'Five Year Housing Land Supply (5YHLS)',
    category: 'Housing',
    definition: 'The requirement for LPAs to demonstrate that they have a deliverable supply of housing sites sufficient for at least five years. A failure to demonstrate this can significantly weaken their position when refusing applications for housing.',
  },
  {
    id: 'flood-plain',
    term: 'Flood Plain',
    category: 'Environment',
    definition: 'Low-lying land prone to flooding, identified in planning for risk assessment. Development here requires careful scrutiny.',
  },
  {
    id: 'flood-risk-assessment-fra',
    term: 'Flood Risk Assessment (FRA)',
    category: 'Environment',
    definition: 'A report required for developments in areas at risk of flooding (Flood Zones 2 or 3) or for sites over 1 hectare in Flood Zone 1. It assesses the flood risk to and from the development and proposes mitigation measures.',
  },
  {
    id: 'front-loading',
    term: 'Front Loading',
    category: 'Planning Policy',
    definition: 'Involving stakeholders early in the planning process. Aims to address issues before formal plan submission.',
  },
  {
    id: 'full-planning-permission',
    term: 'Full Planning Permission',
    category: 'Development',
    definition: 'A single, detailed application for planning permission that covers all aspects of the proposed development. No further consent for reserved matters is required if granted.',
  },
  {
    id: 'general-permitted-development-order-gpdo',
    term: 'General Permitted Development Order (GPDO)',
    category: 'Legal',
    definition: 'Legislation granting automatic permission for certain minor developments.'
  },
  {
    id: 'government-circulars',
    term: 'Government Circulars',
    category: 'Planning Policy',
    definition: 'Guidance issued by the government to clarify planning policies or laws. Less common now but still relevant for specific issues.',
  },
  {
    id: 'green-belt',
    term: 'Green Belt',
    category: 'Land Use',
    definition: 'A designation for land around certain cities and large built-up areas, which aims to prevent urban sprawl by keeping land permanently open. There is a general presumption against inappropriate development within it.',
  },
  {
    id: 'greenfield-land',
    term: 'Greenfield Land',
    category: 'Land Use',
    definition: 'Undeveloped land, typically in the countryside or on the edge of a built-up area, that has not been previously developed. This includes agricultural land.',
  },
  {
    id: 'greenfield-site',
    term: 'Greenfield Site',
    category: 'Land Use',
    definition: 'Land that has not been previously developed, often agricultural.'
  },
  {
    id: 'grey-belt',
    term: 'Grey Belt',
    category: 'Land Use',
    definition: 'Green Belt land that is previously developed or does not strongly serve Green Belt purposes. Proposed for development under specific conditions.',
  },
  {
    id: 'gypsy-and-traveller-accommodation-assessment-gtaa',
    term: 'Gypsy and Traveller Accommodation Assessment (GTAA)',
    category: 'Housing',
    definition: 'A study to identify the housing needs of Gypsy and Traveller communities.',
  },
  {
    id: 'habitable-rooms',
    term: 'Habitable Rooms',
    category: 'Housing',
    definition: 'Rooms in a dwelling used for living, sleeping, or dining. Used to measure housing density or development scale.',
  },
  {
    id: 'habitats-regulations-assessment-hra',
    term: 'Habitats Regulations Assessment (HRA)',
    category: 'Environment',
    definition: 'An assessment required for any plan or project that may affect a "Habitats Site" (also known as a European Site, e.g., Special Areas of Conservation). It determines whether a proposal will adversely affect the integrity of the site.',
  },
  {
    id: 'heritage-asset',
    term: 'Heritage Asset',
    category: 'Heritage',
    definition: 'A building, monument, or site of historic or cultural value.',
  },
  {
    id: 'heritage-statement',
    term: 'Heritage Statement',
    category: 'Heritage',
    definition: 'A report assessing a development’s impact on heritage assets like listed buildings or conservation areas.',
  },
  {
    id: 'highway-authority',
    term: 'Highway Authority',
    category: 'Legal',
    definition: 'The body responsible for maintaining public roads, pavements, and access.'
  },
  {
    id: 'historic-parks-and-gardens',
    term: 'Historic Parks and Gardens',
    category: 'Heritage',
    definition: 'Landscapes of historic interest listed by Historic England. Protected in planning to preserve their character.',
  },
  {
    id: 'houses-in-multiple-occupation-hmos',
    term: 'Houses in Multiple Occupation (HMOs)',
    category: 'Housing',
    definition: 'Properties occupied by multiple unrelated households sharing facilities. May require planning permission for conversion.',
  },
  {
    id: 'housing-land-availability-hla',
    term: 'Housing Land Availability (HLA)',
    category: 'Housing',
    definition: 'An assessment of land available for housing development. Informs local plans but does not allocate sites.',
  },
  {
    id: 'human-rights-act',
    term: 'Human Rights Act',
    category: 'Legal',
    definition: 'Legislation protecting basic freedoms, relevant to balancing individual and community rights in planning.'
  },
  {
    id: 'independent-examination',
    term: 'Independent Examination',
    category: 'Legal',
    definition: 'A formal review of a local or neighbourhood plan by an independent inspector. Ensures the plan is sound and legally compliant.',
  },
  {
    id: 'informal-hearing',
    term: 'Informal Hearing',
    category: 'Legal',
    definition: 'A less formal appeal process where parties discuss a proposal with an inspector. No cross-examination, unlike a public inquiry.',
  },
  {
    id: 'infrastructure',
    term: 'Infrastructure',
    category: 'Development',
    definition: 'The basic physical and organisational structures and facilities needed for the operation of a society or enterprise. In planning, this includes transport, communications, water, sewage, energy systems, and community facilities like schools and hospitals.',
  },
  {
    id: 'infrastructure-act-2015',
    term: 'Infrastructure Act 2015',
    category: 'Legal',
    definition: 'Legislation to simplify planning for infrastructure and housing.'
  },
  {
    id: 'infrastructure-funding-statement',
    term: 'Infrastructure Funding Statement',
    category: 'Development',
    definition: 'An annual report produced by a local authority which provides a summary of all financial contributions collected from developers for infrastructure and affordable housing.',
  },
  {
    id: 'infrastructure-planning-commission-ipc',
    term: 'Infrastructure Planning Commission (IPC)',
    category: 'Legal',
    definition: 'A former body for deciding major infrastructure projects. Now replaced by the Planning Inspectorate’s major projects team.',
  },
  {
    id: 'injunction',
    term: 'Injunction',
    category: 'Enforcement',
    definition: 'A court order sought by an LPA to restrain an actual or apprehended breach of planning control. This is a serious enforcement step taken where there is a risk of significant harm and other enforcement powers are deemed insufficient.',
  },
  {
    id: 'inspector',
    term: 'Inspector',
    category: 'Legal',
    definition: 'An independent planner from the Planning Inspectorate who decides appeals or examines plans.'
  },
  {
    id: 'issues-options-and-preferred-options',
    term: 'Issues, Options and Preferred Options',
    category: 'Planning Policy',
    definition: 'Stages in local plan preparation where development choices are consulted on. Shapes the draft plan before formal submission.',
  },
  {
    id: 'judicial-review-jr',
    term: 'Judicial Review (JR)',
    category: 'Legal',
    definition: 'A legal process where a person can challenge the lawfulness of a decision made by a public body, such as a local planning authority or the Secretary of State. It is concerned with how a decision was made, not the merits of the decision itself.',
  },
  {
    id: 'key-diagram',
    term: 'Key Diagram',
    category: 'Planning Policy',
    definition: 'A visual representation of a local plan’s spatial strategy. Shows broad locations for development without precise boundaries.',
  },
  {
    id: 'key-worker-housing',
    term: 'Key Worker Housing',
    category: 'Housing',
    definition: 'Affordable housing for essential workers like teachers or nurses. Often prioritized in local plans or Section 106 agreements.',
  },
  {
    id: 'lawful-development-certificate-ldc',
    term: 'Lawful Development Certificate (LDC)',
    category: 'Legal',
    definition: 'A legal document issued by an LPA confirming that a proposed or existing use, operation, or activity is lawful for planning purposes. It is not a grant of permission but a confirmation of the legal status.',
  },
  {
    id: 'listed-building',
    term: 'Listed Building',
    category: 'Heritage',
    definition: 'A building or structure officially designated as being of special architectural or historic interest. Any work that would alter its character requires Listed Building Consent.',
  },
  {
    id: 'listed-building-consent',
    term: 'Listed Building Consent',
    category: 'Heritage',
    definition: 'A specific type of consent required from the LPA before any works can be undertaken for the demolition, alteration, or extension of a listed building that would affect its special character.',
  },
  {
    id: 'local-area-agreements-laas',
    term: 'Local Area Agreements (LAAs)',
    category: 'Planning Policy',
    definition: 'Former agreements to align local services with community needs. Now largely replaced by community strategies.',
  },
  {
    id: 'local-development-framework-ldf',
    term: 'Local Development Framework (LDF)',
    category: 'Planning Policy',
    definition: 'A set of documents replacing older structure plans, guiding local development.'
  },
  {
    id: 'local-development-order-ldo',
    term: 'Local Development Order (LDO)',
    category: 'Legal',
    definition: 'An order granting planning permission for specific types of development in a defined area.',
  },
  {
    id: 'local-development-scheme-lds',
    term: 'Local Development Scheme (LDS)',
    category: 'Planning Policy',
    definition: 'A plan outlining the local authority’s schedule for producing planning documents.'
  },
  {
    id: 'local-enterprise-partnership-lep',
    term: 'Local Enterprise Partnership (LEP)',
    category: 'Planning Policy',
    definition: 'A body to promote economic growth, now largely replaced by local authorities.'
  },
  {
    id: 'local-plan',
    term: 'Local Plan',
    category: 'Planning Policy',
    definition: 'A document produced by a Local Planning Authority (LPA) that sets out the long-term vision and framework for development in their area. It includes policies and proposals for how land should be used, forming the primary basis for planning decisions.',
  },
  {
    id: 'local-planning-authority-lpa',
    term: 'Local Planning Authority (LPA)',
    category: 'Legal',
    definition: 'The local government body, typically a district or borough council, responsible for planning and development control in its area. They are the primary decision-makers for most planning applications.',
  },
  {
    id: 'local-strategic-partnerships-lsps',
    term: 'Local Strategic Partnerships (LSPs)',
    category: 'Planning Policy',
    definition: 'Groups coordinating local organizations to deliver community strategies. Influence planning through collaborative priorities.',
  },
  {
    id: 'localism',
    term: 'Localism',
    category: 'Planning Policy',
    definition: 'The principle of devolving planning powers to local communities and authorities.',
  },
  {
    id: 'localism-act-2011',
    term: 'Localism Act 2011',
    category: 'Legal',
    definition: 'Legislation empowering local communities in planning decisions.'
  },
  {
    id: 'locally-listed-buildings',
    term: 'Locally Listed Buildings',
    category: 'Heritage',
    definition: 'Buildings of local significance, not statutorily listed. Protected through local plan policies, not national law.',
  },
  {
    id: 'massing',
    term: 'Massing',
    category: 'Development',
    definition: 'An architectural term referring to the general shape, form, and size of a building or group of buildings. It is a key design consideration in planning, particularly in relation to the impact on the surrounding area.',
  },
  {
    id: 'masterplan',
    term: 'Masterplan',
    category: 'Development',
    definition: 'A long-term planning document that provides a conceptual layout to guide future growth and development. It is about making the connection between buildings, social settings, and their surrounding environments.',
  },
  {
    id: 'material-change-of-use',
    term: 'Material Change of Use',
    category: 'Land Use',
    definition: 'A significant change in how a building or land is used.'
  },
  {
    id: 'material-consideration',
    term: 'Material Consideration',
    category: 'Legal',
    definition: 'A matter that is relevant to the determination of a planning application and must be taken into account by the decision-maker. Key examples include planning policies, overlooking/loss of privacy, highway safety, and previous planning decisions.',
  },
  {
    id: 'minerals-and-waste-plan',
    term: 'Minerals and Waste Plan',
    category: 'Planning Policy',
    definition: 'A plan prepared by a mineral and waste planning authority which sets out the policies to be used for guiding and controlling minerals and waste management development.',
  },
  {
    id: 'minor-material-amendment-mma',
    term: 'Minor Material Amendment (MMA)',
    category: 'Development',
    definition: 'An application made under Section 73 of the Town and Country Planning Act to develop land without complying with a condition previously imposed. It is commonly used to seek permission for minor material changes to an approved scheme.',
  },
  {
    id: 'mitigation',
    term: 'Mitigation',
    category: 'Environment',
    definition: 'Measures taken to reduce or offset a development’s negative impacts, such as environmental harm.',
  },
  {
    id: 'multi-area-agreements-maas',
    term: 'Multi Area Agreements (MAAs)',
    category: 'Planning Policy',
    definition: 'Former agreements for cross-authority collaboration on planning issues. Now less common due to localism reforms.',
  },
  {
    id: 'national-development-framework-ndf',
    term: 'National Development Framework (NDF)',
    category: 'Planning Policy',
    definition: 'Wales’ national plan guiding major development decisions.'
  },
  {
    id: 'national-indicators',
    term: 'National Indicators',
    category: 'Planning Policy',
    definition: 'Metrics to monitor local authority performance, including planning. Largely replaced by other reporting systems post-2010.',
  },
  {
    id: 'national-landscape',
    term: 'National Landscape',
    category: 'Conservation',
    definition: 'Formerly AONB, protected for its natural beauty and cultural value.'
  },
  {
    id: 'national-parks',
    term: 'National Parks',
    category: 'Conservation',
    definition: 'Protected areas for their natural beauty and recreational value. Planning is tightly controlled to preserve their character.',
  },
  {
    id: 'national-planning-policy-framework-nppf',
    term: 'National Planning Policy Framework (NPPF)',
    category: 'Planning Policy',
    definition: "The government's core planning policies for England, setting out the framework within which locally-prepared plans for housing and other development can be produced. It champions a presumption in favour of sustainable development.",
  },
  {
    id: 'neighbour-notification',
    term: 'Neighbour Notification',
    category: 'Legal',
    definition: 'Informing nearby residents about a planning application. Ensures community input before a decision is made.',
  },
  {
    id: 'neighbourhood-forum',
    term: 'Neighbourhood Forum',
    category: 'Planning Policy',
    definition: 'A community group preparing a neighbourhood plan in areas without parish councils.'
  },
  {
    id: 'neighbourhood-plan',
    term: 'Neighbourhood Plan',
    category: 'Planning Policy',
    definition: 'A plan prepared by a parish council or neighbourhood forum which sets out planning policies for a specific local area. Once adopted, it becomes part of the statutory development plan and is used in making decisions on planning applications.',
  },
  {
    id: 'new-homes-bonus',
    term: 'New Homes Bonus',
    category: 'Housing',
    definition: 'A government grant to local authorities for increasing housing stock.'
  },
  {
    id: 'non-material-amendment-nma',
    term: 'Non-Material Amendment (NMA)',
    category: 'Development',
    definition: 'A formal application to make a very minor change to a granted planning permission, which is not considered to have a material impact on the scheme or its external appearance. It cannot be used to vary a condition.',
  },
  {
    id: 'office-of-the-deputy-prime-minister-odpm',
    term: 'Office of the Deputy Prime Minister (ODPM)',
    category: 'Legal',
    definition: 'A former government department overseeing planning policy. Replaced by the Ministry for Housing, Communities and Local Government.',
  },
  {
    id: 'outline-application',
    term: 'Outline Application',
    category: 'Development',
    definition: 'A planning application establishing the principle of development with details reserved.'
  },
  {
    id: 'outline-planning-permission',
    term: 'Outline Planning Permission',
    category: 'Development',
    definition: 'Consent which establishes the principle of a development, including its use and scale, without committing to the final detailed design. The outstanding details are dealt with in a subsequent "Reserved Matters" application.',
  },
  {
    id: 'parish-council',
    term: 'Parish Council',
    category: 'Legal',
    definition: 'A local government body representing a community in planning matters.'
  },
  {
    id: 'parish-plans',
    term: 'Parish Plans',
    category: 'Planning Policy',
    definition: 'Community-led plans outlining local priorities, often influencing planning. Not statutory but may inform neighbourhood plans.',
  },
  {
    id: 'party-wall-act-1996',
    term: 'Party Wall Act 1996',
    category: 'Legal',
    definition: 'A legal framework that provides a process for preventing and resolving disputes in relation to party walls, boundary walls and excavations near neighbouring buildings. It requires serving notice on neighbours before work starts.',
  },
  {
    id: 'pendleton-criteria',
    term: 'Pendleton Criteria',
    category: 'Legal',
    definition: 'Guidelines for assessing planning appeals, focusing on material considerations. Used by inspectors to ensure consistent decisions.',
  },
  {
    id: 'permitted-development',
    term: 'Permitted Development',
    category: 'Development',
    definition: 'Development allowed without formal planning permission under the General Permitted Development Order.',
  },
  {
    id: 'permitted-development-rights-pdr',
    term: 'Permitted Development Rights (PDR)',
    category: 'Development',
    definition: 'A national grant of planning permission which allows certain types of development to be carried out without needing to make a formal planning application. These rights are subject to specific conditions and limitations.',
  },
  {
    id: 'planning-appeal',
    term: 'Planning Appeal',
    category: 'Legal',
    definition: 'The process by which an applicant can challenge a decision made by a Local Planning Authority, such as a refusal of permission or the imposition of conditions. Appeals are determined by the Planning Inspectorate.',
  },
  {
    id: 'planning-committee',
    term: 'Planning Committee',
    category: 'Legal',
    definition: 'A committee of elected councillors who make decisions on major or controversial planning applications that have not been determined by officers under delegated powers. Meetings are held in public.',
  },
  {
    id: 'planning-contravention-notice-pcn',
    term: 'Planning Contravention Notice (PCN)',
    category: 'Enforcement',
    definition: 'A formal notice served by an LPA to request information about activities on land where a breach of planning control is suspected. It is used to establish facts before the authority decides on further enforcement action.',
  },
  {
    id: 'planning-delivery-grant-pdg',
    term: 'Planning Delivery Grant (PDG)',
    category: 'Development',
    definition: 'A former government grant rewarding local authorities for efficient planning. Discontinued but historically supported performance.',
  },
  {
    id: 'planning-inspectorate-pins',
    term: 'Planning Inspectorate (PINS)',
    category: 'Legal',
    definition: 'A government agency that deals with planning appeals, national infrastructure planning applications, examinations of local plans and other planning-related and specialist casework in England and Wales. They act on behalf of the Secretary of State.',
  },
  {
    id: 'planning-obligation-section-106-agreement',
    term: 'Planning Obligation (Section 106 Agreement)',
    category: 'Legal',
    definition: 'A legal agreement (often Section 106) to mitigate a development’s impact.',
  },
  {
    id: 'planning-performance-agreements-ppas',
    term: 'Planning Performance Agreements (PPAs)',
    category: 'Development',
    definition: 'Agreements between applicants and authorities to manage complex applications. Set timelines and resources for efficient processing.',
  },
  {
    id: 'planning-permission',
    term: 'Planning Permission',
    category: 'Development',
    definition: 'Formal consent from a Local Planning Authority for the erection or alteration of buildings or the material change of use of land or buildings. It is required for any activity defined as "development".',
  },
  {
    id: 'planning-policy-guidance-notes-ppgs',
    term: 'Planning Policy Guidance Notes (PPGs)',
    category: 'Planning Policy',
    definition: 'Former government guidance on planning, replaced by the NPPF. Still referenced in older planning documents.',
  },
  {
    id: 'planning-policy-statement-pps',
    term: 'Planning Policy Statement (PPS)',
    category: 'Planning Policy',
    definition: 'Former government guidance on planning policies, now largely replaced by the NPPF.',
  },
  {
    id: 'planning-portfolio-holder',
    term: 'Planning Portfolio Holder',
    category: 'Legal',
    definition: 'A councillor responsible for overseeing the planning function in a council. Acts as a lead on planning policy and decisions.',
  },
  {
    id: 'planning-register',
    term: 'Planning Register',
    category: 'Legal',
    definition: 'A public record of all planning applications and decisions. Maintained by local authorities for transparency.',
  },
  {
    id: 'pre-application-advice',
    term: 'Pre-application Advice',
    category: 'Development',
    definition: 'Advice sought from the LPA by a potential applicant before submitting a formal planning application. This process can help identify key issues and improve the quality of the final submission.',
  },
  {
    id: 'presumption-in-favour-of-sustainable-development',
    term: 'Presumption in Favour of Sustainable Development',
    category: 'Planning Policy',
    definition: 'The core principle of the NPPF. It means that development proposals that accord with an up-to-date development plan should be approved without delay, and where the plan is absent, silent, or out-of-date, permission should be granted unless adverse impacts would significantly outweigh the benefits.',
  },
  {
    id: 'previously-developed-land',
    term: 'Previously Developed Land',
    category: 'Land Use',
    definition: 'Same as Brownfield Land, used for buildings or infrastructure.'
  },
  {
    id: 'prior-approval',
    term: 'Prior Approval',
    category: 'Development',
    definition: 'A process for certain developments under permitted development rights.',
  },
  {
    id: 'prior-notification',
    term: 'Prior Notification',
    category: 'Development',
    definition: 'A requirement to inform the local authority of certain permitted developments.'
  },
  {
    id: 'public-inquiry',
    term: 'Public Inquiry',
    category: 'Legal',
    definition: 'A formal hearing led by a Planning Inspector to examine significant planning issues or appeals.',
  },
  {
    id: 'public-realm',
    term: 'Public Realm',
    category: 'Development',
    definition: 'The publicly owned spaces between buildings, including streets, squares, parks, and other open spaces. The quality of the public realm is a key consideration in urban design and planning.',
  },
  {
    id: 'public-right-of-way-prow',
    term: 'Public Right of Way (PROW)',
    category: 'Access',
    definition: 'A route over which the public has a right to pass and re-pass. This includes footpaths, bridleways, and byways, and their existence is a material consideration in planning.',
  },
  {
    id: 'public-service-agreements-psas',
    term: 'Public Service Agreements (PSAs)',
    category: 'Planning Policy',
    definition: 'Former agreements to improve public service delivery, including planning. Now largely replaced by other frameworks.',
  },
  {
    id: 'public-transport-accessibility-levels-ptals',
    term: 'Public Transport Accessibility Levels (PTALs)',
    category: 'Development',
    definition: 'A measure of access to public transport for a site. Influences planning decisions to promote sustainable travel.',
  },
  {
    id: 'regional-assemblies',
    term: 'Regional Assemblies',
    category: 'Planning Policy',
    definition: 'Former bodies coordinating regional planning, now abolished. Replaced by local authority-led planning systems.',
  },
  {
    id: 'regional-planning-guidance-rpgs',
    term: 'Regional Planning Guidance (RPGs)',
    category: 'Planning Policy',
    definition: 'Pre-2010 regional planning policies, now replaced by local plans. Guided strategic development before localism reforms.',
  },
  {
    id: 'regional-spatial-strategy-rss',
    term: 'Regional Spatial Strategy (RSS)',
    category: 'Planning Policy',
    definition: 'A former strategic plan setting regional housing and employment targets. Replaced by local plans after the Localism Act 2011.'
  },
  {
    id: 'registered-social-landlords-rsls',
    term: 'Registered Social Landlords (RSLs)',
    category: 'Housing',
    definition: 'Organizations like housing associations providing affordable housing. Often involved in delivering planning obligations.',
  },
  {
    id: 'reserved-matters',
    term: 'Reserved Matters',
    category: 'Development',
    definition: 'The detailed aspects of a proposal that are submitted for approval following the granting of outline planning permission. These typically include access, appearance, landscaping, layout, and scale.',
  },
  {
    id: 'retail-impact-assessment',
    term: 'Retail Impact Assessment',
    category: 'Development',
    definition: 'An evaluation of a retail development’s impact on existing town centers. Ensures compliance with the sequential test.',
  },
  {
    id: 'retrospective-planning-application',
    term: 'Retrospective Planning Application',
    category: 'Enforcement',
    definition: 'An application for planning permission for a development that has already been carried out without permission. Submitting such an application does not guarantee that permission will be granted.',
  },
  {
    id: 'ribbon-development',
    term: 'Ribbon Development',
    category: 'Development',
    definition: 'The practice of building houses along the frontages of roads, often extending outwards from towns. This type of development is generally resisted by modern planning policy as it is considered inefficient and unsustainable.',
  },
  {
    id: 'royal-town-planning-institute-rtpi',
    term: 'Royal Town Planning Institute (RTPI)',
    category: 'Legal',
    definition: 'The professional body for planners in the UK. Sets standards and accredits planning professionals.',
  },
  {
    id: 'rural-exception-site',
    term: 'Rural Exception Site',
    category: 'Housing',
    definition: 'A small site for affordable housing, located on land that would not normally be used for housing, such as land in the Green Belt or open countryside. They are permitted as an "exception" to normal policy to meet a proven local need.',
  },
  {
    id: 'scheduled-monument',
    term: 'Scheduled Monument',
    category: 'Heritage',
    definition: 'A nationally important archaeological site or historic building, given protection against unauthorised change. Any works require Scheduled Monument Consent from the Secretary of State, administered by Historic England.',
  },
  {
    id: 'section-104-agreement',
    term: 'Section 104 Agreement',
    category: 'Legal',
    definition: 'A legal agreement under the Water Industry Act 1991 between a developer and a sewerage undertaker (the local water company). It provides a mechanism for the undertaker to adopt new sewers and drainage systems built by the developer.',
  },
  {
    id: 'section-106-agreement-s106',
    term: 'Section 106 Agreement (S106)',
    category: 'Legal',
    definition: 'A legally binding agreement, also known as a "planning obligation," made between a developer and a local planning authority. It is used to mitigate the impact of a development, often securing contributions towards infrastructure or affordable housing.',
  },
  {
    id: 'section-278-agreement',
    term: 'Section 278 Agreement',
    category: 'Legal',
    definition: 'A section of the Highways Act 1980 that allows a developer to carry out works on the public highway to facilitate their development. This is used for works like creating new junctions, access points, or roundabouts.',
  },
  {
    id: 'section-38-agreement',
    term: 'Section 38 Agreement',
    category: 'Legal',
    definition: 'A section of the Highways Act 1980 that allows a developer to construct new roads and have them adopted by the highway authority as public highways once completed to a satisfactory standard. This is common for new housing estates.',
  },
  {
    id: 'secretary-of-state',
    term: 'Secretary of State',
    category: 'Legal',
    definition: 'The central government minister responsible for the Department for Levelling Up, Housing and Communities. They have the power to "call in" and decide major planning applications and to determine certain appeals.',
  },
  {
    id: 'self-build-and-custom-housebuilding',
    term: 'Self-build and Custom Housebuilding',
    category: 'Housing',
    definition: 'Projects where an individual or an association of individuals build or commission the construction of their own home. Local authorities are required to keep a register of people interested in self-build in their area.',
  },
  {
    id: 'sequential-test',
    term: 'Sequential Test',
    category: 'Planning Policy',
    definition: 'A process to ensure development is directed to the most suitable sites, often for retail or flood risk.',
  },
  {
    id: 'setting',
    term: 'Setting',
    category: 'Heritage',
    definition: 'The context in which a heritage asset or feature is experienced.'
  },
  {
    id: 'setting-of-a-heritage-asset',
    term: 'Setting (of a Heritage Asset)',
    category: 'Heritage',
    definition: 'The surroundings in which a heritage asset is experienced. Its extent is not fixed and may change as the asset and its surroundings evolve. Harm to the setting can be a reason for refusing planning permission.',
  },
  {
    id: 'shadow-flicker',
    term: 'Shadow Flicker',
    category: 'Environment',
    definition: 'A phenomenon where wind turbine blades cast moving shadows on nearby properties.'
  },
  {
    id: 'simplified-planning-zone-spz',
    term: 'Simplified Planning Zone (SPZ)',
    category: 'Legal',
    definition: 'An area where specific developments are pre-approved to streamline the planning process.',
  },
  {
    id: 'site-allocation',
    term: 'Site Allocation',
    category: 'Planning Policy',
    definition: 'The designation of land for a particular use in a development plan. This provides certainty to landowners and developers about where development will be acceptable.',
  },
  {
    id: 'site-of-special-scientific-interest-sssi',
    term: 'Site of Special Scientific Interest (SSSI)',
    category: 'Environment',
    definition: 'A conservation designation denoting a protected area in the UK. SSSIs are the basic building block of site-based nature conservation legislation and most other legal nature/geological conservation designations are based upon them.',
  },
  {
    id: 'site-plan',
    term: 'Site Plan',
    category: 'Development',
    definition: 'A detailed plan showing the layout of a proposed development, including the location of buildings, roads, parking, and landscaping.',
  },
  {
    id: 'sites-of-nature-conservation-importance-snci',
    term: 'Sites of Nature Conservation Importance (SNCI)',
    category: 'Environment',
    definition: 'Locally designated sites for wildlife or geological value. Protected through local plan policies.',
  },
  {
    id: 'spatial-development-strategy-sds',
    term: 'Spatial Development Strategy (SDS)',
    category: 'Planning Policy',
    definition: 'A strategic plan for large-scale development, often in cities like London. Guides land use and infrastructure planning.',
  },
  {
    id: 'spatial-planning',
    term: 'Spatial Planning',
    category: 'Planning Policy',
    definition: 'A method of planning aimed at the spatial organisation of land use, going beyond traditional land use planning to bring together and integrate policies for the development and use of land with other policies and programmes which influence the nature of places and how they function.',
  },
  {
    id: 'special-area-of-conservation-sac',
    term: 'Special Area of Conservation (SAC)',
    category: 'Conservation',
    definition: 'A site protected under European law for its habitat or species.'
  },
  {
    id: 'special-protection-area-spa',
    term: 'Special Protection Area (SPA)',
    category: 'Conservation',
    definition: 'A site designated for rare or vulnerable birds under European law.'
  },
  {
    id: 'statement-of-common-ground',
    term: 'Statement of Common Ground',
    category: 'Legal',
    definition: 'A document agreed between parties to outline shared positions in planning appeals or examinations.',
  },
  {
    id: 'statement-of-community-involvement-sci',
    term: 'Statement of Community Involvement (SCI)',
    category: 'Planning Policy',
    definition: 'A document outlining how a local authority will engage the public in planning.'
  },
  {
    id: 'statement-of-consultation',
    term: 'Statement of Consultation',
    category: 'Legal',
    definition: 'A report detailing how consultation shaped a local plan or application. Ensures transparency in the planning process.',
  },
  {
    id: 'statutory-consultee',
    term: 'Statutory Consultee',
    category: 'Legal',
    definition: 'Organisations and public bodies that an LPA has a legal duty to consult on relevant planning applications. Examples include the Environment Agency, Historic England, and National Highways.',
  },
  {
    id: 'statutory-instrument-si',
    term: 'Statutory Instrument (SI)',
    category: 'Legal',
    definition: 'Secondary legislation to enact or amend planning laws without a new Act.'
  },
  {
    id: 'statutory-undertaker',
    term: 'Statutory Undertaker',
    category: 'Legal',
    definition: 'Bodies authorised by Parliament to carry out functions for the public good, such as utility companies (gas, water, electricity), transport operators (e.g., Network Rail), and electronic communications providers. They have certain permitted development rights.',
  },
  {
    id: 'stop-notice',
    term: 'Stop Notice',
    category: 'Enforcement',
    definition: 'A powerful enforcement tool used by an LPA in urgent cases, which demands that a specific activity constituting a breach of planning control ceases immediately. Failure to comply with a Stop Notice is a criminal offence.',
  },
  {
    id: 'strategic-environmental-assessment-sea',
    term: 'Strategic Environmental Assessment (SEA)',
    category: 'Environment',
    definition: 'A systematic process for evaluating the likely significant environmental effects of public plans or programmes, such as a Local Plan. It ensures environmental considerations are integrated at the earliest stage of decision-making.',
  },
  {
    id: 'strategic-housing-land-availability-assessment-shlaa',
    term: 'Strategic Housing Land Availability Assessment (SHLAA)',
    category: 'Housing',
    definition: 'A technical study undertaken by LPAs to identify a supply of specific, deliverable sites that have the potential for housing development. It forms a key part of the evidence base for a Local Plan.',
  },
  {
    id: 'strategic-land',
    term: 'Strategic Land',
    category: 'Development',
    definition: 'Land identified for large-scale development, often involving major infrastructure. This land is typically undeveloped and requires a long-term strategy for its release and development.',
  },
  {
    id: 'strategic-planning',
    term: 'Strategic Planning',
    category: 'Planning Policy',
    definition: 'Long-term planning focused on spatial organisation and development goals for a region, often covering an area larger than a single local authority.',
  },
  {
    id: 'strategic-spatial-planning',
    term: 'Strategic Spatial Planning',
    category: 'Planning Policy',
    definition: 'Long-term planning for large-scale development across regions or districts.'
  },
  {
    id: 'structure-plan',
    term: 'Structure Plan',
    category: 'Planning Policy',
    definition: 'A former strategic plan for counties, now replaced by local plans. Set broad development policies before 2010.',
  },
  {
    id: 'submission-document',
    term: 'Submission Document',
    category: 'Planning Policy',
    definition: 'The final draft of a local plan submitted for examination. Includes supporting evidence and consultation responses.',
  },
  {
    id: 'sui-generis',
    term: 'Sui Generis',
    category: 'Land Use',
    definition: 'A Latin term meaning "of its own kind". In planning, it refers to uses of land or buildings that do not fall into any of the specified use classes in the Use Classes Order. Examples include theatres, nightclubs, and petrol stations.',
  },
  {
    id: 'supplementary-planning-document-spd',
    term: 'Supplementary Planning Document (SPD)',
    category: 'Planning Policy',
    definition: 'Guidance providing detail on local plan policies.',
  },
  {
    id: 'sustainability-appraisal',
    term: 'Sustainability Appraisal',
    category: 'Environment',
    definition: 'An evaluation of a plan’s social, economic, and environmental impacts.',
  },
  {
    id: 'sustainable-communities',
    term: 'Sustainable Communities',
    category: 'Environment',
    definition: 'Neighbourhoods designed to balance social, economic, and environmental needs. A key goal of modern planning policy.',
  },
  {
    id: 'sustainable-community-strategy',
    term: 'Sustainable Community Strategy',
    category: 'Planning Policy',
    definition: 'A plan to improve quality of life in a local area. Informs local plan objectives and priorities.',
  },
  {
    id: 'sustainable-development',
    term: 'Sustainable Development',
    category: 'Environment',
    definition: 'Development balancing economic, social, and environmental needs.'
  },
  {
    id: 'sustainable-drainage-systems-suds',
    term: 'Sustainable Drainage Systems (SuDS)',
    category: 'Environment',
    definition: 'A collection of water management practices that aim to manage surface water runoff in a way that mimics natural drainage. They are designed to reduce flood risk, improve water quality, and enhance biodiversity.',
  },
  {
    id: 'sustainable-urban-drainage-system-suds',
    term: 'Sustainable Urban Drainage System (SUDS)',
    category: 'Environment',
    definition: 'Drainage systems designed to manage surface water sustainably, reducing flood risk.',
  },
  {
    id: 'technical-advice-notes-tans',
    term: 'Technical Advice Notes (TANs)',
    category: 'Planning Policy',
    definition: 'Welsh Government guidance providing detail on national planning policies. Supports local authorities in plan-making and decisions.',
  },
  {
    id: 'thermal-mass',
    term: 'Thermal Mass',
    category: 'Environment',
    definition: 'The ability of a material to absorb and store heat, reducing temperature swings.'
  },
  {
    id: 'town-and-country-planning-act-1990',
    term: 'Town and Country Planning Act 1990',
    category: 'Legal',
    definition: 'The main legislation governing planning in England and Wales. Defines development and sets out the planning permission process.',
  },
  {
    id: 'townscape',
    term: 'Townscape',
    category: 'Development',
    definition: 'The visual appearance and cohesion of a town or city’s elements.'
  },
  {
    id: 'transport-impact-assessment',
    term: 'Transport Impact Assessment',
    category: 'Development',
    definition: 'An evaluation of a development’s impact on transport networks. Required for proposals likely to affect traffic or access.',
  },
  {
    id: 'travel-plans',
    term: 'Travel Plans',
    category: 'Development',
    definition: 'Strategies to promote sustainable transport for a development. May include measures like cycle paths or car-sharing schemes.',
  },
  {
    id: 'tree-preservation-order-tpo',
    term: 'Tree Preservation Order (TPO)',
    category: 'Conservation',
    definition: 'An order made by an LPA to protect specific trees, groups of trees or woodlands in the interests of amenity. It is an offence to cut down, top, lop, uproot, wilfully damage or destroy a protected tree without the authority\'s permission.',
  },
  {
    id: 'twin-tracking-overlapping-applications',
    term: 'Twin Tracking/Overlapping Applications',
    category: 'Development',
    definition: 'Submitting multiple similar applications for the same site. Used to expedite decisions or test different proposals.',
  },
  {
    id: 'unitary-development-plans-udps',
    term: 'Unitary Development Plans (UDPs)',
    category: 'Planning Policy',
    definition: 'Former single-tier plans for unitary authorities, now replaced by local plans. Covered all planning aspects for an area.',
  },
  {
    id: 'urban-development-corporation-udc',
    term: 'Urban Development Corporation (UDC)',
    category: 'Development',
    definition: 'A body set up to regenerate specific urban areas through planning and development powers.',
  },
  {
    id: 'urban-framework-plans',
    term: 'Urban Framework Plans',
    category: 'Development',
    definition: 'Non-statutory plans guiding regeneration in urban areas. Provide a vision for coordinated development.',
  },
  {
    id: 'urban-renaissance-regeneration',
    term: 'Urban Renaissance/Regeneration',
    category: 'Development',
    definition: 'Revitalizing urban areas through planning and development. Aims to improve economic and social conditions.',
  },
  {
    id: 'use-class-order',
    term: 'Use Class Order',
    category: 'Land Use',
    definition: 'Regulations grouping land and building uses into categories.'
  },
  {
    id: 'use-classes-order',
    term: 'Use Classes Order',
    category: 'Land Use',
    definition: 'A statutory instrument that categorises different uses of land and buildings (e.g., shops, offices, residential). Changes of use within the same class do not constitute development and do not require planning permission.',
  },
  {
    id: 'validation-of-a-planning-application',
    term: 'Validation of a Planning Application',
    category: 'Development',
    definition: 'The process by which a local planning authority checks that a submitted planning application meets the statutory national and local requirements before it can be registered and considered.',
  },
  {
    id: 'viability-assessment',
    term: 'Viability Assessment',
    category: 'Development',
    definition: 'An assessment submitted with a planning application to determine whether a proposed development will be financially viable. It is often used to negotiate levels of affordable housing or other planning obligations.',
  },
  {
    id: 'village-design-statement-vds',
    term: 'Village Design Statement (VDS)',
    category: 'Development',
    definition: 'A community-led document guiding development in rural areas. Informs local plan policies to preserve village character.',
  },
  {
    id: 'windfall-site',
    term: 'Windfall Site',
    category: 'Development',
    definition: 'A site not specifically allocated for development in a Local Plan which unexpectedly becomes available for development. LPAs can include an allowance for windfall sites in their housing supply calculations, subject to certain criteria.',
  },
  {
    id: 'zero-carbon-home',
    term: 'Zero Carbon Home',
    category: 'Environment',
    definition: 'A home that produces zero net carbon emissions from all energy use in the home. While once a government target, the definition and policy requirements have evolved over time.',
  },
  {
    id: 'allocated-site',
    term: 'Allocated Site',
    category: 'Land Use',
    definition: 'Land identified in a local plan for specific development, like housing or employment. Guides where growth should occur based on strategic planning.',
  },
  {
    id: 'appropriate-assessment',
    term: 'Appropriate Assessment',
    category: 'Environment',
    definition: 'An evaluation under the Habitats Regulations to assess impacts on protected European sites. Required for developments affecting Special Areas of Conservation or Special Protection Areas.',
  },
  {
    id: 'archaeological-assessment',
    term: 'Archaeological Assessment',
    category: 'Heritage',
    definition: 'A study to evaluate a site’s archaeological significance before development. Required in areas with known or potential historic remains.',
  },
  {
    id: 'area-action-plan-aap',
    term: 'Area Action Plan (AAP)',
    category: 'Planning Policy',
    definition: 'A Development Plan Document focusing on a specific area needing significant change. Guides regeneration or conservation in targeted locations.',
  },
  {
    id: 'building-for-a-healthy-life',
    term: 'Building for a Healthy Life',
    category: 'Development',
    definition: 'A design framework to assess housing schemes for health and wellbeing. Used to ensure developments promote quality living environments.',
  },
  {
    id: 'call-in-procedure',
    term: 'Call-in Procedure',
    category: 'Legal',
    definition: 'The process where the Secretary of State takes over a planning application for decision. Applied to nationally significant or controversial proposals.',
  },
  {
    id: 'character-assessment',
    term: 'Character Assessment',
    category: 'Conservation',
    definition: 'An evaluation of an area’s distinct visual or historic qualities. Informs planning to ensure developments respect local identity.',
  },
  {
    id: 'community-right-to-build-order',
    term: 'Community Right to Build Order',
    category: 'Legal',
    definition: 'A community-led order granting permission for small-scale local projects. Similar to a Neighbourhood Plan but focused on specific developments.',
  },
  {
    id: 'conservation-area-appraisal',
    term: 'Conservation Area Appraisal',
    category: 'Conservation',
    definition: 'A document defining the special character of a Conservation Area. Guides planning decisions to preserve or enhance the area’s qualities.',
  },
  {
    id: 'core-strategy-dpd',
    term: 'Core Strategy DPD',
    category: 'Planning Policy',
    definition: 'A key Development Plan Document outlining the strategic vision for an area. Sets overarching policies for housing, employment, and environment.',
  },
  {
    id: 'cumulative-impact',
    term: 'Cumulative Impact',
    category: 'Environment',
    definition: 'The combined effect of multiple developments on an area’s environment or infrastructure. Considered in planning to avoid overloading local systems.',
  },
  {
    id: 'delegated-decision',
    term: 'Delegated Decision',
    category: 'Legal',
    definition: 'A planning decision made by officers rather than the planning committee. Used for routine or minor applications to streamline the process.',
  },
  {
    id: 'demolition-consent',
    term: 'Demolition Consent',
    category: 'Conservation',
    definition: 'Permission required to demolish buildings in a Conservation Area. Ensures the area’s character is preserved or enhanced.',
  },
  {
    id: 'development-brief',
    term: 'Development Brief',
    category: 'Development',
    definition: 'A document outlining planning requirements for a specific site. Guides developers on expectations for layout, design, or use.',
  },
  {
    id: 'development-management-policies',
    term: 'Development Management Policies',
    category: 'Planning Policy',
    definition: 'Policies in a local plan guiding the assessment of planning applications. Cover issues like design, amenity, or environmental protection.',
  },
  {
    id: 'flood-zone',
    term: 'Flood Zone',
    category: 'Environment',
    definition: 'An area classified by flood risk level, from Zone 1 (low risk) to Zone 3 (high risk). Guides where development is suitable based on flood risk assessments.',
  },
  {
    id: 'general-consultation-bodies',
    term: 'General Consultation Bodies',
    category: 'Legal',
    definition: 'Non-statutory groups, like community organizations, consulted on planning matters. Ensures broader community input beyond statutory consultees.',
  },
  {
    id: 'green-infrastructure',
    term: 'Green Infrastructure',
    category: 'Environment',
    definition: 'Natural and semi-natural features like parks or green corridors in urban areas. Planned to enhance biodiversity, recreation, and climate resilience.',
  },
  {
    id: 'heritage-impact-assessment',
    term: 'Heritage Impact Assessment',
    category: 'Heritage',
    definition: 'A study evaluating a development’s effect on heritage assets. Required for proposals near listed buildings or conservation areas.',
  },
  {
    id: 'housing-delivery-test',
    term: 'Housing Delivery Test',
    category: 'Housing',
    definition: 'An annual assessment of housing delivery against an LPA’s housing requirement. Failure can lead to penalties like the tilted balance in decision-making.',
  },
  {
    id: 'housing-need-assessment',
    term: 'Housing Need Assessment',
    category: 'Housing',
    definition: 'A study to determine the number and type of homes needed in an area. Informs local plan housing targets and policies.',
  },
  {
    id: 'implementation-annex',
    term: 'Implementation Annex',
    category: 'Planning Policy',
    definition: 'An annex in the NPPF explaining how its policies should be applied. Provides practical guidance for planners and developers.',
  },
  {
    id: 'infill-development',
    term: 'Infill Development',
    category: 'Development',
    definition: 'Building on small, vacant plots within existing urban areas. Encouraged to make efficient use of land without sprawling.',
  },
  {
    id: 'infrastructure-delivery-plan-idp',
    term: 'Infrastructure Delivery Plan (IDP)',
    category: 'Development',
    definition: 'A document identifying infrastructure needed to support a local plan’s growth. Covers roads, schools, and utilities to ensure sustainable development.',
  },
  {
    id: 'interim-measures',
    term: 'Interim Measures',
    category: 'Planning Policy',
    definition: 'Temporary planning policies or actions while a new local plan is prepared. Used to address urgent issues like housing shortfalls.',
  },
  {
    id: 'landscape-character-assessment',
    term: 'Landscape Character Assessment',
    category: 'Environment',
    definition: 'A study defining an area’s unique landscape features and qualities. Guides planning to protect or enhance scenic value.',
  },
  {
    id: 'local-development-document-ldd',
    term: 'Local Development Document (LDD)',
    category: 'Planning Policy',
    definition: 'A document forming part of the local development framework, including DPDs and SPDs. Collectively shapes local planning policy and guidance.',
  },
  {
    id: 'local-green-space',
    term: 'Local Green Space',
    category: 'Land Use',
    definition: 'A designation in a local or neighbourhood plan to protect valued green areas. Restricts development to preserve community spaces.',
  },
  {
    id: 'local-nature-reserve-lnr',
    term: 'Local Nature Reserve (LNR)',
    category: 'Environment',
    definition: 'A site designated by an LPA for its local wildlife or geological value. Protected to promote biodiversity and public access to nature.',
  },
  {
    id: 'main-modifications',
    term: 'Main Modifications',
    category: 'Planning Policy',
    definition: 'Significant changes to a draft local plan proposed during examination. Subject to consultation to ensure the plan is sound.',
  },
  {
    id: 'major-development',
    term: 'Major Development',
    category: 'Development',
    definition: 'Large-scale projects defined by criteria like 10+ homes or 1,000 sqm of floorspace. Subject to stricter planning scrutiny and consultation.',
  },
  {
    id: 'mixed-use-development',
    term: 'Mixed-Use Development',
    category: 'Development',
    definition: 'A project combining residential, commercial, or other uses on one site. Promotes vibrant, sustainable communities with diverse functions.',
  },
  {
    id: 'national-planning-practice-guidance-nppg',
    term: 'National Planning Practice Guidance (NPPG)',
    category: 'Planning Policy',
    definition: 'Online government guidance supporting the NPPF’s implementation. Provides detailed advice on specific planning issues like flood risk.',
  },
  {
    id: 'non-designated-heritage-asset',
    term: 'Non-Designated Heritage Asset',
    category: 'Heritage',
    definition: 'A heritage asset not statutorily protected but recognized locally for its value. Considered in planning to preserve local history.',
  },
  {
    id: 'permeability',
    term: 'Permeability',
    category: 'Development',
    definition: 'The ease of movement through a development, like pedestrian or cycle access. Promotes walkable, connected communities in design policies.',
  },
  {
    id: 'planning-balance',
    term: 'Planning Balance',
    category: 'Legal',
    definition: 'The process of weighing material considerations against the development plan. Determines whether permission should be granted or refused.',
  },
  {
    id: 'planning-breach',
    term: 'Planning Breach',
    category: 'Enforcement',
    definition: 'Carrying out development without permission or breaching a condition. May lead to enforcement action by the LPA.',
  },
  {
    id: 'planning-condition',
    term: 'Planning Condition',
    category: 'Legal',
    definition: 'Requirements attached to planning permission to control development. Must be precise, enforceable, and relevant to the proposal.',
  },
  {
    id: 'planning-gain',
    term: 'Planning Gain',
    category: 'Development',
    definition: 'Benefits secured from a development, like affordable housing or infrastructure. Often delivered through Section 106 agreements or CIL.',
  },
  {
    id: 'pre-commencement-condition',
    term: 'Pre-Commencement Condition',
    category: 'Legal',
    definition: 'A planning condition requiring action before development starts. Examples include submitting drainage or landscaping plans.',
  },
  {
    id: 'precedent',
    term: 'Precedent',
    category: 'Legal',
    definition: 'A previous planning decision influencing future similar cases. Not legally binding but can affect consistency in decision-making.',
  },
  {
    id: 'prior-notification-procedure',
    term: 'Prior Notification Procedure',
    category: 'Development',
    definition: 'A process to inform the LPA of certain permitted developments before starting. Allows review of limited impacts like design or neighbors.',
  },
  {
    id: 'public-open-space',
    term: 'Public Open Space',
    category: 'Land Use',
    definition: 'Land designated for public recreation, like parks or playgrounds. Protected in planning to support community wellbeing.',
  },
  {
    id: 'registered-park-or-garden',
    term: 'Registered Park or Garden',
    category: 'Heritage',
    definition: 'A historic park or garden listed for its design or cultural value. Development must consider impacts on its setting and character.',
  },
  {
    id: 'renewable-energy-assessment',
    term: 'Renewable Energy Assessment',
    category: 'Environment',
    definition: 'A study evaluating a development’s potential to use renewable energy sources. Supports sustainable design in line with climate goals.',
  },
  {
    id: 'reserved-matters-application',
    term: 'Reserved Matters Application',
    category: 'Development',
    definition: 'An application detailing layout, scale, or access after outline permission. Must align with the approved outline planning consent.',
  },
  {
    id: 'sequential-approach',
    term: 'Sequential Approach',
    category: 'Planning Policy',
    definition: 'A planning principle prioritizing certain sites, like town centers for retail. Ensures development occurs in the most sustainable locations.',
  },
  {
    id: 'site-allocation-dpd',
    term: 'Site Allocation DPD',
    category: 'Planning Policy',
    definition: 'A Development Plan Document identifying specific sites for development. Details land for housing, employment, or other uses.',
  },
  {
    id: 'site-investigation',
    term: 'Site Investigation',
    category: 'Development',
    definition: 'A technical study of a site’s ground conditions, like contamination or stability. Required to ensure safe and viable development.',
  },
  {
    id: 'soundness',
    term: 'Soundness',
    category: 'Planning Policy',
    definition: 'The test a local plan must pass during examination to be adopted. Ensures it is positively prepared, justified, effective, and consistent with national policy.',
  },
  {
    id: 'statement-of-case',
    term: 'Statement of Case',
    category: 'Legal',
    definition: 'A document submitted during a planning appeal outlining the appellant’s argument. Details why the LPA’s decision should be overturned.',
  },
  {
    id: 'statutory-development-plan',
    term: 'Statutory Development Plan',
    category: 'Planning Policy',
    definition: 'The legally binding set of documents guiding planning decisions. Includes the Local Plan and any made Neighbourhood Plans.',
  },
  {
    id: 'strategic-flood-risk-assessment-sfra',
    term: 'Strategic Flood Risk Assessment (SFRA)',
    category: 'Environment',
    definition: 'A study of flood risks across an LPA’s area to inform planning. Guides site allocations and development management policies.',
  },
  {
    id: 'strategic-housing-market-assessment-shma',
    term: 'Strategic Housing Market Assessment (SHMA)',
    category: 'Housing',
    definition: 'A study of housing needs across a wider market area. Informs housing targets and policies in local plans.',
  },
  {
    id: 'supplementary-planning-guidance-spg',
    term: 'Supplementary Planning Guidance (SPG)',
    category: 'Planning Policy',
    definition: 'Non-statutory guidance in Wales supporting development plan policies. Similar to SPDs but used in the Welsh planning system.',
  },
  {
    id: 'sustainability-statement',
    term: 'Sustainability Statement',
    category: 'Environment',
    definition: 'A report showing how a development meets sustainable development goals. Covers economic, social, and environmental impacts.',
  },
  {
    id: 'sustainable-transport',
    term: 'Sustainable Transport',
    category: 'Development',
    definition: 'Transport modes like walking, cycling, or public transit promoted in planning. Reduces reliance on cars to lower environmental impact.',
  },
  {
    id: 'technical-consultation',
    term: 'Technical Consultation',
    category: 'Legal',
    definition: 'Consultation with statutory consultees on specific planning issues. Ensures expert input on topics like flooding or heritage.',
  },
  {
    id: 'tenure',
    term: 'Tenure',
    category: 'Housing',
    definition: 'The ownership or rental status of housing, like social rent or shared ownership. Considered in planning to meet diverse housing needs.',
  },
  {
    id: 'tilted-balance',
    term: 'Tilted Balance',
    category: 'Planning Policy',
    definition: 'An NPPF policy favoring approval when a local plan is out-of-date. Applies when housing supply or policies fail to meet requirements.',
  },
  {
    id: 'town-centre-first',
    term: 'Town Centre First',
    category: 'Planning Policy',
    definition: 'A policy prioritizing retail and commercial development in town centers. Aims to maintain vibrant high streets and reduce out-of-town sprawl.',
  },
  {
    id: 'transport-statement',
    term: 'Transport Statement',
    category: 'Development',
    definition: 'A report assessing a development’s transport impacts, like traffic or parking. Required for smaller projects, unlike a full Transport Assessment.',
  },
  {
    id: 'tree-survey',
    term: 'Tree Survey',
    category: 'Environment',
    definition: 'A study of trees on a development site to assess their health and value. Informs whether a TPO or mitigation is needed.',
  },
  {
    id: 'urban-capacity-study',
    term: 'Urban Capacity Study',
    category: 'Development',
    definition: 'A study identifying potential for development within urban areas. Helps maximize use of brownfield sites before greenfield development.',
  },
  {
    id: 'use-class-e',
    term: 'Use Class E',
    category: 'Land Use',
    definition: 'A broad use class covering shops, offices, restaurants, and other commercial uses. Allows flexibility in changing uses without planning permission.',
  },
  {
    id: 'viability-appraisal',
    term: 'Viability Appraisal',
    category: 'Development',
    definition: 'An assessment of a development’s financial feasibility. Ensures contributions like affordable housing are deliverable.',
  },
  {
    id: 'village-green',
    term: 'Village Green',
    category: 'Land Use',
    definition: 'A community space protected from development for recreational use. Can be designated through community applications.',
  },
  {
    id: 'vitality-and-viability',
    term: 'Vitality and Viability',
    category: 'Development',
    definition: 'The health and economic strength of town centers. Planning policies aim to enhance these through retail and mixed-use development.',
  },
  {
    id: 'windfall-allowance',
    term: 'Windfall Allowance',
    category: 'Development',
    definition: 'An estimate of housing from unexpected, unallocated sites in a local plan. Contributes to meeting housing targets without specific allocations.',
  },
  {
    id: 'world-heritage-site',
    term: 'World Heritage Site',
    category: 'Heritage',
    definition: 'A UNESCO-designated site of global cultural or natural significance. Planning must protect its outstanding universal value.',
  },
  {
    id: 'zoning',
    term: 'Zoning',
    category: 'Land Use',
    definition: 'Designating areas in a local plan for specific uses, like residential or industrial. Guides development to appropriate locations.',
  },
  {
    id: 'adjoining-authority',
    term: 'Adjoining Authority',
    category: 'Legal',
    definition: 'A neighboring local authority consulted on cross-boundary planning issues. Ensures coordinated planning under the Duty to Cooperate.',
  },
  {
    id: 'affordable-housing-contribution',
    term: 'Affordable Housing Contribution',
    category: 'Housing',
    definition: 'A financial or in-kind contribution to affordable housing via Section 106. Used when on-site housing provision is not feasible.',
  },
  {
    id: 'agricultural-land-classification-alc',
    term: 'Agricultural Land Classification (ALC)',
    category: 'Land Use',
    definition: 'A system grading farmland by quality, from Grade 1 (best) to Grade 5. Influences planning to protect high-quality agricultural land.',
  },
  {
    id: 'air-quality-assessment',
    term: 'Air Quality Assessment',
    category: 'Environment',
    definition: 'A study of a development’s impact on local air quality. Required in areas with pollution concerns to ensure health standards.',
  },
  {
    id: 'area-of-high-landscape-value-ahlv',
    term: 'Area of High Landscape Value (AHLV)',
    category: 'Conservation',
    definition: 'A local designation protecting landscapes of scenic or ecological importance. Restricts development to preserve their character.',
  },
  {
    id: 'brownfield-register',
    term: 'Brownfield Register',
    category: 'Land Use',
    definition: 'A list of previously developed sites suitable for housing. Encourages reuse of brownfield land to meet housing targets.',
  },
  {
    id: 'call-for-sites',
    term: 'Call for Sites',
    category: 'Planning Policy',
    definition: 'A process inviting landowners to propose sites for development in a local plan. Helps identify potential land for housing or other uses.',
  },
  {
    id: 'community-engagement',
    term: 'Community Engagement',
    category: 'Legal',
    definition: 'The process of involving residents in planning decisions or plan-making. Ensures local views shape development outcomes.',
  },
  {
    id: 'conservation-area-character-statement',
    term: 'Conservation Area Character Statement',
    category: 'Conservation',
    definition: 'A document detailing the unique qualities of a Conservation Area. Guides planning to maintain its historic or architectural value.',
  },
  {
    id: 'constraints-map',
    term: 'Constraints Map',
    category: 'Development',
    definition: 'A map showing planning restrictions like Green Belt or flood zones. Helps developers assess a site’s development potential.',
  },
  {
    id: 'developer-contributions',
    term: 'Developer Contributions',
    category: 'Development',
    definition: 'Financial or in-kind benefits from developers to support infrastructure. Secured through CIL or Section 106 agreements.',
  },
  {
    id: 'development-viability',
    term: 'Development Viability',
    category: 'Development',
    definition: 'The financial feasibility of a development project. Assessed to balance planning obligations with project deliverability.',
  },
];

export const getAllTerms = (): PlanningTerm[] => {
  return planningTerms.sort((a, b) => a.term.localeCompare(b.term));
};

export const getTermBySlug = (slug: string): PlanningTerm | undefined => {
  return planningTerms.find(term => term.id === slug);
};
